M48
; DRILL file {KiCad 9.0.5} date 2025-10-27T17:08:35+0530
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2025-10-27T17:08:35+05:30
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.5
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.650
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C1.000
%
G90
G05
T1
X170.18Y-46.68
X175.96Y-46.68
T2
X125.462Y-90.375
X131.463Y-90.375
M30
